import os
from dotenv import load_dotenv

load_dotenv()

CLICKHOUSE_HOST = os.getenv('CLICKHOUSE_HOST')
CLICKHOUSE_USERNAME = os.getenv('CLICKHOUSE_USERNAME')
CLICKHOUSE_PASSWORD = os.getenv('CLICKHOUSE_PASSWORD')
CLICKHOUSE_DATABASE = os.getenv('CLICKHOUSE_DATABASE')

print(CLICKHOUSE_HOST)
print(CLICKHOUSE_USERNAME)
print(CLICKHOUSE_PASSWORD)
print(CLICKHOUSE_DATABASE)
